### ISSUE TITLE
how to enter queries as a string (cf mongo --eval 'db.data.find({"foo":1})' 

### ISSUE THREAD

**Issue by timotheecour** [2night/mondo#4]
```

Query q = new Query();
q.fields["foo"] = true;
q.sorts["bar"] = 1;
assert(q.JsonString == `find({"foo" : 1}).sort("bar" : 1)`);

auto q2=Query.parse(`find({"foo": {"$lt" : 0.5} }, {"bar":0}).sort({"age":-1}).limit(3)`);
auto ret = c.eval(q2);
```

**Comment by trikko** [comment]
Not easy to do, mongodb syntax its quite strange, not standard json:

For example:
{a: 2}
find({"foo" : 1})
{"test" : ObjectId("123123123")}

Query string can contain also js that we should check and parse too. I think it's too complex and error prone :)

**Comment by timotheecour** [comment]
how about either:
- using a wrapper around function that achieves this in mongo client library
- defining an alternative syntax of your choice for this (could be pure json)

Use cases: allowing one to use it command line interfaces, or as a search box in web UI's, serializing queries, etc.
