### ISSUE TITLE
how to parse BsonObject from string?

### ISSUE THREAD

**Issue by timotheecour** [2night/mondo#5]
This would provide a direct solution to https://github.com/2night/mondo/issues/4

EDIT: got it to work by converting to vibe.data.bson.Bson, would be nice to use Bson from this package instead of rolling your own; vibe.data.bson.Bson seems to have better support

**Comment by trikko** [comment]
This is a different job. This can be done. :)

**Comment by trikko** [comment]
Fixed

**Comment by timotheecour** [comment]
great! could you please reference the commit/PR or reference this bug from within the commit msg so it automatically shows up here :)

**Comment by trikko** [comment]
Yes but i forgot, of course

Il 02 nov 2016 7:40 PM, "Timothee Cour" notifications@github.com ha
scritto:

**Comment by timotheecour** [comment]
https://github.com/2night/mondo/commit/16c64251a5eca35a641e16a493c889273aa55090
