### ISSUE TITLE
DateTime field

### ISSUE THREAD

**Issue by zafer06** [2night/mondo#9]
Hello. Great work. Thank you for this. How can I write and read datetime field with mondo.

**Comment by trikko** [comment]
Sorry I didn't notice this. I fixed a related issue. You can simply read it using

yourobj["field"].as!BsonDateTime  
yourobj["field"].get!BsonDateTime  
yourobj["field"].to!BsonDateTime  

(or SysTime. BsonDateTime is just an alias)
